### ISSUE TITLE
Module cvxopt is an invisible dependency

### ISSUE THREAD

**Issue by ehultee** [BryanRiel/iceutils#2]
When I set up iceutils as described in the README and run a minimal example, I receive the error:
>Traceback (most recent call last):
  File "helheim-extract_ts.py", line 5, in `<module>`
    import iceutils as ice
  File "/home/ehultee/.conda/envs/ehu-gld/lib/python3.7/site-packages/iceutils/__init__.py", line 12, in `<module>`
    from . import tseries
  File "/home/ehultee/.conda/envs/ehu-gld/lib/python3.7/site-packages/iceutils/tseries/__init__.py", line 4, in `<module>`
    from .LinearRegression import *
  File "/home/ehultee/.conda/envs/ehu-gld/lib/python3.7/site-packages/iceutils/tseries/LinearRegression.py", line 6, in `<module>`
    from cvxopt import solvers, matrix, sparse, spmatrix, log, div, blas
ModuleNotFoundError: No module named 'cvxopt'

The cvxopt package is not listed in requirements.txt nor in the README.

**Comment by BryanRiel** [comment]
Just added `cvxopt` as a requirement to the README with commit [1a1cda7](https://github.com/BryanRiel/iceutils/commit/1a1cda758eb9730f335b7ecd53e25676f3d13b1c)
